In [2]:
from numpy import array

#ndarray is a N dimensional array

a = [1, 2, 3]
a = array(a)
print(a)
print(a.shape)
print(a.dtype)
print(type(a))

[1 2 3]
(3,)
int32
<class 'numpy.ndarray'>


In [2]:
from numpy import empty

a = empty([3,3])
print(a)

[[ 1.48749568e-272  2.91725233e+236  7.94797035e-304]
 [-3.10564605e+232  2.15425082e+236  2.15482440e+236]
 [ 7.94797046e-304 -3.10564605e+232 -4.64334410e+083]]


In [4]:
from numpy import zeros
from numpy import ones

a = zeros([3,3])
print(a)

a = ones([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
from numpy import vstack
from numpy import hstack

a1 = array([1,2,3])
a2 = array([4,5,6])

a3 = vstack((a1,a2))
print(a3)
print(a3.shape)

a3 = hstack((a1,a2))
print(a3)
print(a3.shape)

#Notice how shape says 6, for the horizontal array, which is 6 columns 1 row. But 2,3 for the 2 row 3 column array

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]
(6,)


In [19]:
a = [[1,2,3],[1,2,3]]
a = array(a)
print(a)
print(a[0])
print(a[-1])
print(a[-1,2])
print(a[0:2,0])

[[1 2 3]
 [1 2 3]]
[1 2 3]
[1 2 3]
3
[1 1]


In [21]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a = array(a)
print(a)

print(a[:,:-1])
print(a[:,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[3 6 9]


In [22]:
split = 2

train,test = a[:split,:], a[split,:]
print(train)
print(test)

[[1 2 3]
 [4 5 6]]
[7 8 9]


In [33]:
a = array([1,2,3,4,5])
print(a)
print(a.shape)
a = array([[1,2,3,4,5],[1,2,3,4,5]])
print(a)
print(a.shape)
print("cols: %d" %a.shape[1])

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)
cols: 5


In [36]:
a = array([1,2,3,4,5,6])
print(a)
print(a.shape)

a = a.reshape((a.shape[0],1))
print(a)

a = a.reshape(3,2)
print(a)

[1 2 3 4 5 6]
(6,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2]
 [3 4]
 [5 6]]


In [46]:
data = [[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]]
data = array(data)

print(data)

data.reshape(3, data.shape[1], 2)

print(data)

data.reshape(6, data.shape[1], 1)

print(data)

#3 dimensional array could be used for multiple time steps, with an observation with multiple characteristics at each time step
# Or multiple samples at multiple time steps, with each sample having some features

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [5]:
# Adding 1 dimensional array to 1 dimensional array
a = array([1,2,3])
b = array([1,2,3])
c = a+b
print(c)

#Adding 2 dimensional array to 2 dimensional array
a = array([[1,2,3],[4,5,6]])
b = array([[1,2,3],[4,5,6]])
c = a+b
print(c)

[2 4 6]
[[ 2  4  6]
 [ 8 10 12]]


In [6]:
#Broadcasting
#Adding 1D array to a scalar
a = 5
b = array([1,2,3])
print(a+b)

[6 7 8]


In [7]:
#Add 2d array to a scalar
a = 5
b = array([[1,2,3],[4,5,6]])
print(a+b)

[[ 6  7  8]
 [ 9 10 11]]


In [8]:
#Add 1d array to a 2d array
a = array([1,2,3])
b = array([[1,2,3],[4,5,6]])
print(a+b)

[[2 4 6]
 [5 7 9]]
