In [3]:
from numpy import array


#vector addition
a = array([1,2,3])
b = array([1,2,3])

c = a+b
print(c)

#vector subtraction
c = a-b
print(c)

#vector multiplication
c = a*b
print(c)

#vector division
c = a/b
print(c)

#dot product
c = a.dot(b)
print(c)

#vector times scalar
c = 5
d = c*a
print(d)

[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]
14
[ 5 10 15]


In [14]:
from numpy.linalg import norm
from math import inf

a = array([1,2,3])

# taxicab norm
l1 = norm(a,1)
print(l1)


# Euclidean norm
l2 = norm(a)
print(l2)

# Max norm
l3 = norm(a, inf)
print(l3)

6.0
3.7416573867739413
3.0


In [2]:
# Matrix Addition

A = array([[1,2,3],[4,5,6]])
B = array([[1,2,3],[4,5,6]])

print(A+B)

[[ 2  4  6]
 [ 8 10 12]]


In [4]:
#Matrix Subtraction
print(A-B)

[[0 0 0]
 [0 0 0]]


In [5]:
#Hadamard Product
print(A*B)

[[ 1  4  9]
 [16 25 36]]


In [7]:
#Matrix Division
C = A/B
print(C)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#Matrix Multiplication

A = array([[1,2,3],[4,5,6]])
B = array([[1,2,3],[4,5,6],[7,8,9]])

C = A.dot(B)
print(C)

C = A@B
print(C)

#Same thing for matrix*vector multiplication

[[30 36 42]
 [66 81 96]]
[[30 36 42]
 [66 81 96]]


In [12]:
#Matrix times scalar
C = 2
D = A*C
print(D)

[[ 2  4  6]
 [ 8 10 12]]


In [14]:
from numpy import tril
from numpy import triu

B = array([[1,2,3],[4,5,6],[7,8,9]])

#lower triangular matrix
A = tril(B)
print(A)

#upper triangular matrix
C = triu(B)
print(C)

[[1 0 0]
 [4 5 0]
 [7 8 9]]
[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [16]:
#Get a diagonal vector
from numpy import diag

A = diag(B)
print(A)

#construct diagonal matrix
A = diag(A)
print(A)

[1 5 9]
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [17]:
#identity matrix
from numpy import identity
a = identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
from numpy.linalg import inv

#Example of orthogonal matrix
a = array([[1,0],[0,-1]])

#Transpose of orthogonal matrix equals the inverse
inverse = inv(a)
transpose = a.T

print(a, inverse, transpose)

#orthogonal matrix times the transpose equals the identity
print(a.dot(transpose))

[[ 1  0]
 [ 0 -1]] [[ 1.  0.]
 [-0. -1.]] [[ 1  0]
 [ 0 -1]]
[[1 0]
 [0 1]]


In [34]:
A = array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [22]:
#transpose
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [35]:
#inverse
A = A[:,:2]
print(A)
print(inv(A))
print(A@inv(A))

[[1 2]
 [4 5]]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
[[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]


In [28]:
#trace
from numpy import trace
print(trace(A))

6


In [29]:
#determinant
from numpy.linalg import det
print(det(A))

-2.9999999999999996


In [36]:
#rank
from numpy.linalg import matrix_rank
print(matrix_rank(A))

A = array([[1,0],[1,0]])
print(matrix_rank(A))

2
1


In [46]:
#Converting a sparse matrix using CSR (compressed sparse row) method

a = array([[1,0,0,1,0,0],[0,0,2,0,0,1],[0,0,0,2,0,0]])
print(a)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [47]:
from scipy.sparse import csr_matrix
S = csr_matrix(a)
print(S)

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [48]:
B = S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [49]:
#calculate sparsity
from numpy import count_nonzero
sparsity = 1 - count_nonzero(a)/a.size
print(sparsity)

0.7222222222222222


In [50]:
#3 dimensional tensor

t = array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(t)
print(t.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)


In [51]:
#tensor arithmetic
b = t+t
print(b)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]


In [52]:
#tensor subtraction
c = t-t
print(c)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [53]:
#tensor hadamard product
c = t*t
print(c)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[100 121 144]
  [169 196 225]
  [256 289 324]]

 [[361 400 441]
  [484 529 576]
  [625 676 729]]]


In [54]:
#tensor division
c = t/t
print(c)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [57]:
# tensor multiplication
from numpy import tensordot

A = array([[1,2],[3,4]])
B = array([[1,2],[3,4]])
C = tensordot(A,B, axes = 0)
print(A)
print(B)
print(C)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[[[ 1  2]
   [ 3  4]]

  [[ 2  4]
   [ 6  8]]]


 [[[ 3  6]
   [ 9 12]]

  [[ 4  8]
   [12 16]]]]
