In [2]:
from numpy import array
from scipy.linalg import lu

A = array([[1,2,3],[4,5,6],[7,8,9]])

#LU decomposition
P,L,U = lu(A)

print(A)
print(P)
print(L)
print(U)
print(P@L@U)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [3]:
#QR decomposition

from numpy.linalg import qr

Q, R = qr(A, 'complete')
print(A)
print(Q)
print(R)
print(Q.dot(R))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [5]:
#Cholesky decomposition
from numpy.linalg import cholesky

A = array([[2,1,1],[1,2,1],[1,1,2]])
print(A)

L = cholesky(A)
print(L)

print(L.dot(L.T))

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


In [9]:
#Eigendecomposition

from numpy.linalg import eig

A = array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

values, vectors = eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [10]:
#Confirm eigenvectors and values

#Retrieve the first eigenvector
first = vectors[:,0]

#Multiply it through the original matrix A
B = A.dot(first)

print(B)

#Retrieve the first eigenvalue
value = values[0]

#multiply the first eigenvalue by the first eigenvector, to scale it the same magnitude by which the A matrix scales it
print(first*value)


[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


In [14]:
#Reconstruct matrix with eigenvectors

from numpy import diag
from numpy.linalg import inv

inverse_eigen = inv(vectors)
print(inverse_eigen)

#create diagonal matrix from eigenvalues
diagonal = diag(values)
print(diagonal)

#Reconstruct the A matrix
print(vectors@diagonal@inverse_eigen)

[[-0.48295226 -0.59340999 -0.70386772]
 [-0.91788599 -0.24901003  0.41986593]
 [ 0.40824829 -0.81649658  0.40824829]]
[[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.38433605e-16]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [17]:
#Singular Value Decomposition

from scipy.linalg import svd

A = array([[1,2],[3,4],[5,6]])

print(A)

U, s, V = svd(A)

print(U)
print(s)
print(V)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [21]:
from numpy import zeros

# Create sigma matrix with the right dimensions
Sigma = zeros((A.shape[0], A.shape[1]))
print(Sigma)

#Put in the singular values along the diagonal (if A was a square matrix, you could use the diag(s) matrix directly)
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
print(diag(s))
print(Sigma)

#Reconstruct the original matrix
print(U.dot(Sigma.dot(V)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[9.52551809 0.        ]
 [0.         0.51430058]]
[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [22]:
#psuedoinverse
from numpy.linalg import pinv

A = array([[1,2],[3,4],[5,6]])

print(A)
print(pinv(A))

[[1 2]
 [3 4]
 [5 6]]
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [24]:
#Creating the pseudoinverse manually
U, s, V = svd(A)

d = 1 / s
print(d)

D = zeros(A.shape)
D[:A.shape[1], :A.shape[1]] = diag(d)

pseudo = V.T.dot(D.T).dot(U.T)
print(pseudo)

[0.10498117 1.94438824]
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [28]:
#Dimensionality Reduction

A = array([[1,2,3,4,5,6],[7,8,9,11,12,13],[14,15,16,17,18,19]])
print(A)

U, s, V = svd(A)

Sigma = zeros((A.shape[0], A.shape[1]))
Sigma[:A.shape[0], :A.shape[0]] = diag(s)

#Select only the first two features
n_elements = 2
Sigma = Sigma[:, :n_elements]
V = V[:n_elements, :]

#reconstruct with only two features
new = U.dot(Sigma.dot(V))
print(new)

#two equivalent transforms/summaries/projections of the original matrix
print(U.dot(Sigma))
print(A.dot(V.T))

[[ 1  2  3  4  5  6]
 [ 7  8  9 11 12 13]
 [14 15 16 17 18 19]]
[[ 1.0749546   1.95622505  2.8374955   4.16336     5.04463045  5.9259009 ]
 [ 6.91066455  8.05217365  9.19368276 10.80529761 11.94680672 13.08831582]
 [14.03823803 14.97766824 15.91709846 17.08333797 18.02276819 18.9621984 ]]
[[ -9.08621178  -2.89355218]
 [-25.00013219  -1.70195078]
 [-40.59688228   1.69570712]]
[[ -9.08621178  -2.89355218]
 [-25.00013219  -1.70195078]
 [-40.59688228   1.69570712]]


In [29]:
#Using Scikit learn to create the transforms
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=2)

svd.fit(A)

result = svd.transform(A)
print(result)

[[ 9.08621178  2.89355218]
 [25.00013219  1.70195078]
 [40.59688228 -1.69570712]]
